# -*- coding: utf-8 -*-
"""Linear_Regression_Single_Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsMvpCas36ylcWy1sSdlZqOUF5Iqzvr5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('/content/homeprices.csv')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area(sqr ft)')
plt.ylabel('price(US$)')
plt.scatter(df.area,df.price,color='red',marker='+')

reg = linear_model.LinearRegression()
# reg.fit(df[['area']],df.price)
reg.fit(df[['area']],df.price)

# reg.predict(3300)//given error
reg.predict([[3300]])

# y = mx+c, m = 135.78767123
reg.coef_

# y = mx+c, c = 180616.43835616432 
reg.intercept_

# y = mx+c
135.78767123*3300+180616.43835616432

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area',fontsize=20)
plt.ylabel('price',fontsize=20)
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')

d = pd.read_csv("/content/areas.csv")
d.head(3)

p = reg.predict(d)

d['prices'] = p

d.to_csv("prediction.csv")

"""Exercise"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("/content/canada_per_capita_income.csv")
#df
df.head(5)

df.columns
# # df = df.rename(columns={'per capita income (US$) ': 'income'})
# df = pd.read_csv('/content/canada_per_capita_income.csv', delim_whitespace=True)

df.head(5)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('income(US$)')
plt.scatter(df.year,df.per capita income (US$),color='red',marker='+')

